version: '3.8'
services:
  digital-signage:
      build: .
          container_name: digital-signage
              volumes:
                    - signage_content:/var/www/digital-signage/content/videos
                          - signage_api:/va
